### ISSUE TITLE
outdated link

### ISSUE THREAD

**Issue by Pat054** [gmasse/diematic#3]
Hello Gmasse,

I don't know if this is the right place to converse ...

Here is the link http://www.wit-square.fr/forum/topics/de-dietrich-communication-modbus-bi-ma-tre is out of date "404 error ..."

Anyway, where can you find the modscan software?

Thank you again for this work. cordially

Patric

**Comment by gmasse** [comment]
Thanks @Pat054 for reporting the broken link. Unfortunately, the entire website seems down.
I don't use modscan, so I can't answer.
