### ISSUE TITLE
Trying to interpret burners and other "bits" values

### ISSUE THREAD

**Issue by piwai** [gmasse/diematic#6]
Hi @gmasse 

After reading the different modbus tables I coud find, I currently get the following dashboard:
![screenshot_heater](https://user-images.githubusercontent.com/3604235/107154973-1ab41900-6976-11eb-80cc-f53ed8adafcc.png)
The corresponding dashboard exported as .json file: 

[heater.json](https://github.com/gmasse/diematic/files/5939663/heater.json.log)

Now I'm trying to understand the meaning of the "bits" value, (registers starting from index 700), but I'm puzzled. Is there actually several "burners"  in a single heater, each one with a power level on 2 bits, so from 0 to 3 ? Or are the burners starting from 2 only active when you have several heaters using cascading mode? Judging by the screenshot you added, and as I get mostly zeroes when quering them, I would tend to favor the 2nd solution.
Would you also please share your dashboard .json export file? I would also be interested in understanding other values like pumps, alarms, etc... But contrary to the temperature values, this seems to be more specific and potentially different from one heater model to another.

Thanks

**Comment by gmasse** [comment]
Very good question. I haven't looked deeper into power level of burners, so I can't answer.
My dashboard just show the bits without more understanding (moreover I lost the json when I migrated to grafana 😅).

**Comment by piwai** [comment]
@gmasse ok, thanks. Any reason to prefer Grafana over Chronograf?

**Comment by gmasse** [comment]
@piwai Grafana seems a bit more mobile friendly. Also at one point I thought about developing specific visualization plugins.

**Comment by piwai** [comment]
ok, thanks. Well, closing this one, as I did not make any progress on these burners flags for now.
